export default {
  login: "Rentoshiro",
  id: 149387302,
  node_id: "U_kgDOCOd4Jg",
  avatar_url: "https://avatars.githubusercontent.com/u/149387302?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Rentoshiro",
  html_url: "https://github.com/Rentoshiro",
  followers_url: "https://api.github.com/users/Rentoshiro/followers",
  following_url:
    "https://api.github.com/users/Rentoshiro/following{/other_user}",
  gists_url: "https://api.github.com/users/Rentoshiro/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Rentoshiro/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Rentoshiro/subscriptions",
  organizations_url: "https://api.github.com/users/Rentoshiro/orgs",
  repos_url: "https://api.github.com/users/Rentoshiro/repos",
  events_url: "https://api.github.com/users/Rentoshiro/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Rentoshiro/received_events",
  type: "User",
  site_admin: false,
  name: "RentoShiro",
  company: "Coding Addict",
  blog: "",
  location: "Germany",
  email: null,
  hireable: null,
  bio: "Creator of Coding Addict",
  twitter_username: "",
  public_repos: 25,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};
